name: db test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: pgweb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            sleep 2
          done

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run SQL to check row count
        run: |
          export PGPASSWORD=postgres
          count=$(psql -h localhost -U postgres -d pgweb -t -c "SELECT COUNT(*) FROM my_table;" | xargs)
          echo "Row count is $count"
          if [ "$count" -ne 10 ]; then
            echo "Expected 10 rows but got $count"
            exit 1
          fi